# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Fabric API
fabric_api_version=0.161.0+26.3

# Mod Properties
mod_version=1.0.0
maven_group=net.aoba
archives_base_name=Aoba

# Dependencies
netty_version=4.2.15.Final

# Sodium (https://github.com/CaffeineMC/sodium-fabric)
sodium_version=mc26.3-0.9.2-fabric

# Lithium (https://github.com/CaffeineMC/lithium-fabric)
lithium_version=mc26.3-0.26.2-fabric

# Iris (https://github.com/IrisShaders/Iris)
iris_version=1.11.6+26.3-fabric

# Mod Menu (https://github.com/TerraformersMC/ModMenu)
modmenu_version=21.0.0
